# -*- coding: utf-8 -*-
"""Untitled82.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k0XrD12c1w4_5q0DL5DiUBAH1GiK7PjD
"""

# -*- coding: utf-8 -*-

def greeting(name):
  print("Hello, " + name)

person1 = {
  "name": "John",
  "age": 36,
  "country": "Norway"
}